SAK-34005 - Certification tool - Allow to overwrite unassigned templa…
sakaicontrib/certification pull request #16
Opened 2018-03-09 12:29 UTC by danielmerino

…te fields with custom values

2018-03-09 14:54 UTC, bjones86 requested changes
Functionally this looks good to me. Just a few blocks have some tabs/spaces issues.

I also noticed that the Travis CI failed due to some of the Mock services being out of date (unrelated to the changes here). If you have time to update those while you're in there, that would be great. Otherwise I'll fix them up in a follow up PR.

2018-03-09 14:54 UTC, bjones86 commented on tool/src/main/webapp/WEB-INF/jsp/createCertificateFour.jsp
> +        					</c:if>
Looks like there's some tabs/spaces inconsistency here.

2018-03-09 14:54 UTC, bjones86 commented on tool/src/main/webapp/WEB-INF/jsp/createCertificateThree.jsp
> +                                    </c:if>
And in this block.

2018-03-13 09:54 UTC, danielmerino commented
@bjones86 thanks for the review, I have fixed the format. Sorry, I haven't never developed Mock services and I'm afraid I will spend a lot of time in doing it...

2018-03-13 13:59 UTC, bjones86 commented
No problem, @danielmerino. It's really not related to this PR anyway, so I'll submit another PR later to fix them up. Thanks!

2018-03-13 13:59 UTC, bjones86 approved these changes

2018-03-13 15:09 UTC, merged